apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o1mrqkzh4-go 
  janus-idp.io/tekton: o1mrqkzh4-go
  backstage.io/kubernetes-id: o1mrqkzh4-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o1mrqkzh4-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  